<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.31" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="VersOne.Epub" Version="3.3.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AudiobookConverter.Application\AudiobookConverter.Application.csproj" />
    <ProjectReference Include="..\AudiobookConverter.Domain\AudiobookConverter.Domain.csproj" />
  </ItemGroup>

</Project>
